services:
  bot-mnamer:
    build:
      context: ./bot-net
      dockerfile: Dockerfile
    container_name: bot-mnamer
    restart: unless-stopped
    env_file:
      - .env
    args:
        - PUID=${PUID:-1000}
        - GUID=${PGID:-1000}
    user: "${PUID:-1000}:${PGID:-1000}"
    volumes:
      - /mnt/disco:/data
